Repository cardano-foundation/cardano-rosetta-java, pull requests merged in 2025-06, with the labels that each got.

#449 feat: enhance stability test with error threshold and additional metrics
  load-tests/README.MD
  load-tests/stability_test.py
Labels: enhancement, tests

#482 chore: Spring 3.5 for API and Yaci-Indexer
  pom.xml
Labels: needs QA

#478 docs: misc docusaurus improvements
  README.md
  docs/docs/advanced-configuration/pruning.md
  docs/docs/core-concepts/cardano-addons.md
  docs/docs/development/performance-measurements.md
  docs/docs/development/qa-regression.md
  docs/docs/development/test-results/1.2.6-dev_2025-04-16/docker-compose.md
  docs/docs/development/test-results/1.2.6-dev_2025-04-16/single-docker.md
  docs/docs/development/test-results/1.2.6/docker-compose.md
  docs/docs/development/test-results/1.2.6/single-docker.md
  docs/docs/development/test-results/1.2.7/docker-compose.md
  docs/docs/development/test-results/1.2.7/single-docker.md
  docs/docs/development/test-results/1.2.9/docker-compose.md
  docs/docs/development/test-results/1.2.9/huge-address-1.6M.md
  docs/docs/development/test-results/1.2.9/huge-address-373k.md
  docs/docs/development/test-results/1.2.9/single-docker.md
  docs/docs/install-and-deploy/docker.md
  docs/docs/install-and-deploy/env-vars.md
  docs/docs/install-and-deploy/hardware-profiles.md
  docs/docs/intro.md
  docs/docs/user-guides/multi-assets.md
  docs/docusaurus.config.js
  docs/package.json
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/static/api.yaml
  docs/yarn.lock
Labels: documentation, needs QA
