Repository cardano-foundation/cardano-rosetta-java, pull requests merged in 2025-03, with the labels that each got.

#292 fix: fixed incorrect tx size and tx fee calculations
  .env.IntegrationTest
  .env.docker-compose
  api/pom.xml
  api/src/main/java/org/cardanofoundation/rosetta/RosettaApiApplication.java
  api/src/main/java/org/cardanofoundation/rosetta/api/account/controller/AccountApiImplementation.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/controller/BlockApiImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/controller/ConstructionApiImplementation.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionService.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiService.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ProtocolParamsConverter.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ProtocolParamsConverterImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/network/controller/NetworkApiImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/network/mapper/NetworkMapperUtils.java
  api/src/main/java/org/cardanofoundation/rosetta/api/search/controller/SearchApiImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/common/enumeration/NetworkEnum.java
  api/src/main/java/org/cardanofoundation/rosetta/common/exception/ExceptionFactory.java
  api/src/main/java/org/cardanofoundation/rosetta/common/time/OfflineSlotService.java
  api/src/main/java/org/cardanofoundation/rosetta/common/time/OfflineSlotServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/RosettaConstants.java
  api/src/main/java/org/cardanofoundation/rosetta/config/CardanoConvertersConfig.java
  api/src/main/java/org/cardanofoundation/rosetta/config/NetworkConfig.java
  api/src/main/java/org/cardanofoundation/rosetta/config/TimeConfig.java
  api/src/test/java/org/cardanofoundation/rosetta/api/BaseSpringMvcSetup.java
  api/src/test/java/org/cardanofoundation/rosetta/api/IntegrationTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/TestConfig.java
  api/src/test/java/org/cardanofoundation/rosetta/api/TransactionsTestData.java
  api/src/test/java/org/cardanofoundation/rosetta/api/account/controller/AccountApiImplementationTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/controller/BlockApiImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/controller/ConstructionApiImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/CombineApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/MetadataApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/PayloadsApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/PreprocessApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/ProtocolParamsConverterImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/SubmitApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/network/controller/NetworkApiDelegateImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/search/controller/SearchControllerTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/cache/ProtocolParamsCacheTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/enumeration/NetworkEnumTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/mapper/ProtocolParamsConverterTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/time/OfflineSlotServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/util/CborEncodeUtilTest.java
  pom.xml
  postmanTests/rosetta-java.postman_collection.json
Labels: In QA

#316 feat: simple performance / scalability fixes.
  api/src/main/java/org/cardanofoundation/rosetta/api/account/service/AccountServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/service/BlockServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/network/service/NetworkServiceImpl.java
  api/src/main/resources/config/application-online.yaml
Labels: Performance Improvement

#321 feat: exposing configuration variables for yaci-store prunning inside of rosetta yaci indexer
  .env.IntegrationTest
  .env.docker-compose
  .env.h2
  api/src/test/resources/config/application-test-integration.yaml
  docker-compose-api.yaml
  docker-compose-indexer.yaml
  docker/.env.dockerfile
  yaci-indexer/src/main/resources/application.properties
  yaci-indexer/src/test/resources/application-test-integration.properties
Labels: Performance Improvement, QA approved, Quick Win

#330 feat: small scalability improvements for a typical exchange setup.
  api/src/main/resources/config/application-online.yaml
Labels: Quick Win

#307 feat: dRep vote delegation support (transaction construction)
  api/pom.xml
  api/src/main/java/org/cardanofoundation/rosetta/api/block/mapper/BlockMapper.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/mapper/TransactionMapper.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/mapper/TransactionMapperUtils.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/model/domain/BlockTx.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/model/domain/DRepDelegation.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/model/domain/ProcessOperations.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/model/domain/ProcessOperationsReturn.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/model/domain/StakePoolDelegation.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/service/BlockServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionService.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiService.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/OperationService.java
  api/src/main/java/org/cardanofoundation/rosetta/api/network/controller/NetworkApiImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/common/enumeration/OperationType.java
  api/src/main/java/org/cardanofoundation/rosetta/common/exception/ExceptionFactory.java
  api/src/main/java/org/cardanofoundation/rosetta/common/mapper/util/OperationMapperService.java
  api/src/main/java/org/cardanofoundation/rosetta/common/model/cardano/CertificateWithAddress.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/CardanoAddressUtils.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/Constants.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/MoreEnums.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/OperationParseUtil.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/ProcessConstructions.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/RosettaConstants.java
  api/src/main/resources/rosetta-specifications-1.4.15/api.json
  api/src/main/resources/rosetta-specifications-1.4.15/api.yaml
  api/src/test/java/org/cardanofoundation/rosetta/api/block/mapper/BlockToBlockResponseTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/mapper/BlockTxToBlockTxResponseTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/mapper/BlockTxToRosettaTransactionTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/BlockServiceImplIntTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImplIntTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/ParseApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/PayloadsApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/PreprocessApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/util/MoreEnumsTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/util/ParseOperationTest.java
  api/src/test/resources/testdata/construction/Operations/drepDelegationOperation-abstain.json
  api/src/test/resources/testdata/construction/Operations/drepDelegationOperation-keyhash.json
  api/src/test/resources/testdata/construction/Operations/drepDelegationOperation-noconfidence.json
  api/src/test/resources/testdata/construction/Operations/drepDelegationOperation-scripthash.json
  api/src/test/resources/testdata/construction/payloads/dRep_delegation.json
  api/src/test/resources/testdata/construction/preprocess/drep_vote_delegation.json
  pom.xml
  postmanTests/rosetta-java.postman_collection.json
Labels: enhancement, In QA

#337 refactor: common executor services defined once and re-used.
  api/src/main/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/config/ThreadPoolsConfig.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImplTest.java
  docker/entrypoint.sh
  yaci-indexer/src/main/java/org/cardanofoundation/rosetta/yaciindexer/resource/AccountController.java
  yaci-indexer/src/main/java/org/cardanofoundation/rosetta/yaciindexer/service/AccountServiceImpl.java
Labels: needs QA

#338 refactor: dependencies update.
  api/pom.xml
  pom.xml
  yaci-indexer/pom.xml
Labels: needs QA

#339 refactor: do not use cpu bound thread pool, context switching between threads is not cheap.
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/config/ThreadPoolsConfig.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/CombineApiTest.java
Labels: needs QA

#350 feat: explicit db pool config
  .env.IntegrationTest
  .env.docker-compose
  .env.h2
  api/src/main/resources/config/application-online.yaml
  api/src/test/resources/config/application-test-integration.yaml
  docker-compose-api.yaml
  docker/.env.dockerfile
Labels: needs QA

#351 feat: add end-to-end testing framework for Cardano Rosetta API
  e2e-tests/.env.example
  e2e-tests/.gitignore
  e2e-tests/README.md
  e2e-tests/pyproject.toml
  e2e-tests/pytest.ini
  e2e-tests/requirements.txt
  e2e-tests/rosetta_client/__init__.py
  e2e-tests/rosetta_client/client.py
  e2e-tests/rosetta_client/exceptions.py
  e2e-tests/tests/__init__.py
  e2e-tests/tests/conftest.py
  e2e-tests/tests/stake_operations.py
  e2e-tests/tests/test_multi_asset_transactions.py
  e2e-tests/tests/test_multi_io_transactions.py
  e2e-tests/tests/test_stake_scenarios.py
  e2e-tests/wallet_utils/__init__.py
  e2e-tests/wallet_utils/pycardano_wallet.py
Labels: enhancement, Non Functional Requirement

#348 chore: prepare 1.2.5 release
  .env.IntegrationTest
  .env.docker-compose
  .env.h2
  README.md
  api/pom.xml
  api/src/main/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/config/ThreadPoolsConfig.java
  api/src/main/resources/config/application-online.yaml
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/CombineApiTest.java
  api/src/test/resources/config/application-test-integration.yaml
  docker-compose-api.yaml
  docker/.env.dockerfile
  docker/entrypoint.sh
  pom.xml
  yaci-indexer/pom.xml
  yaci-indexer/src/main/java/org/cardanofoundation/rosetta/yaciindexer/resource/AccountController.java
  yaci-indexer/src/main/java/org/cardanofoundation/rosetta/yaciindexer/service/AccountServiceImpl.java
  yaci-indexer/src/main/resources/db/store/postgresql/V1.0_900_0__rosetta_app_addres_utxo.sql
Labels: QA approved

#363 refactor: fail faster and less code complexity due to structured concurrency.
  api/Dockerfile
  api/pom.xml
  api/src/main/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/common/exception/ExceptionFactory.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/RosettaConstants.java
  api/src/main/java/org/cardanofoundation/rosetta/config/ThreadPoolsConfig.java
  api/src/test/java/org/cardanofoundation/rosetta/api/TestConfig.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/BlockServiceImplIntTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImplIntTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/block/service/LedgerBlockServiceImplTest.java
  docker/entrypoint.sh
Labels: Performance Improvement, needs QA, needs scalability test, Ready For Release Testing

#356 feat: 10.1.4 by default also for a single docker image.
  api/src/test/resources/config/application-test-integration.yaml
  docker/dockerfiles/node/Dockerfile
  docker/readme.md
Labels: Non Functional Requirement, needs QA, Quick Win, Ready For Release Testing

#361 fix: payload endpoint must use original rosetta fee calculation.
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionService.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiServiceImpl.java
  api/src/main/java/org/cardanofoundation/rosetta/common/util/Constants.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/CardanoConstructionServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/ConstructionApiServiceImplTest.java
  api/src/test/java/org/cardanofoundation/rosetta/api/construction/service/PayloadsApiTest.java
  api/src/test/java/org/cardanofoundation/rosetta/common/util/CborEncodeUtilTest.java
  postmanTests/rosetta-java.postman_collection.json
Labels: QA approved

#366 feat: initialize documentation structure and deployment workflow
  .github/workflows/deploy-docs.yml
  docs/.gitignore
  docs/README.md
  docs/docs/advanced/_category_.json
  docs/docs/advanced/configuration-and-performance.md
  docs/docs/api/_category_.json
  docs/docs/api/cardano-specific-additions.md
  docs/docs/architecture/_category_.json
  docs/docs/architecture/media/ComponentDiagram.drawio.svg
  docs/docs/architecture/media/ContextDiagram.drawio.svg
  docs/docs/architecture/overview.md
  docs/docs/contributing/_category_.json
  docs/docs/contributing/index.md
  docs/docs/development/_category_.json
  docs/docs/development/performance/_category_.json
  docs/docs/development/performance/db-tuning.md
  docs/docs/development/performance/measurements.md
  docs/docs/development/qa/_category_.json
  docs/docs/development/qa/regression.md
  docs/docs/development/qa/rosetta-cli-tests.md
  docs/docs/getting-started/_category_.json
  docs/docs/getting-started/docker.md
  docs/docs/getting-started/environment-variables.md
  docs/docs/getting-started/h2.md
  docs/docs/getting-started/install-cardano-node.md
  docs/docs/intro.md
  docs/docs/legacy-docs/MAINTAINER.MD
  docs/docs/legacy-docs/QA.md
  docs/docs/legacy-docs/_category_.json
  docs/docs/legacy-docs/catalyst-vote-support.md
  docs/docs/legacy-docs/multi-assets-support.md
  docs/docs/legacy-docs/pool-operations-support.md
  docs/docs/legacy-docs/rosetta-custom-definitions.md
  docs/docs/legacy-docs/staking-support.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/GitHubStats/index.js
  docs/src/components/GitHubStats/styles.module.css
  docs/src/components/HomepageFeatures/index.js
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/api.yaml
  docs/static/img/api-interface-svgrepo-com.svg
  docs/static/img/cardano-starburst-blue.svg
  docs/static/img/cloud-acceleration-svgrepo-com.svg
  docs/static/img/favicon.ico
  docs/static/img/multiple-defenses-svgrepo-com.svg
  docs/yarn.lock
Labels: documentation, enhancement

#365 Add e2e test for fixed fee scenario
  e2e-tests/README.md
  e2e-tests/pyproject.toml
  e2e-tests/pytest.ini
  e2e-tests/requirements.txt
  e2e-tests/rosetta_client/client.py
  e2e-tests/tests/conftest.py
  e2e-tests/tests/test_multi_io_transactions.py
Labels: enhancement

#371 feat: connection pooling for http connections.
  api/src/main/java/org/cardanofoundation/rosetta/config/HttpConfig.java
Labels: needs QA, needs scalability test

#376 feat: enhance stability testing framework with CLI options, delays, and expanded test cases
  load-tests/.gitignore
  load-tests/README.MD
  load-tests/data/mainnet-data-huge-address.csv
  load-tests/data/mainnet-data-stake-address.csv
  load-tests/data/mainnet-data.csv
  load-tests/stability_test.py
Labels: enhancement
